Update config ci/cd pipeline

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -160,12 +160,12 @@ jobs:
       - name: Make gradlew executable
         run: chmod +x ./gradlew
 
-      - name: Cache SonarCloud packages
-        uses: actions/cache@v4
-        with:
-          path: ~/.sonar/cache
-          key: ${{ runner.os }}-sonar
-          restore-keys: ${{ runner.os }}-sonar
+#      - name: Cache SonarCloud packages
+#        uses: actions/cache@v4
+#        with:
+#          path: ~/.sonar/cache
+#          key: ${{ runner.os }}-sonar
+#          restore-keys: ${{ runner.os }}-sonar
 
       - name: Download coverage report
         uses: actions/download-artifact@v4
@@ -178,6 +178,13 @@ jobs:
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
+          if [ -z "$SONAR_TOKEN" ]; then
+            echo "::error:: ERROR: SONAR_TOKEN is not set or is empty!"
+            echo "::error:: Please make sure you have saved SONAR_TOKEN under 'Repository secrets'."
+            exit 1
+          else
+            echo "SONAR_TOKEN has been successfully loaded."
+          fi
           ./gradlew sonar --no-daemon -Dsonar.token=$SONAR_TOKEN
         continue-on-error: true
 
